'#include <stdio.h>\n'
'#include "prime.h"\n'
'\n'
'int main(int argc, char *argv[])\n'
'{\n'
'    for (int i = -1; i < 65537; ++i)\n'
'        if (is_prime_number(i))\n'
'            fprintf(stdout, "%d is prime.\\n", i);\n'
'    \n'
'    return 0;\n'
'}\n'
