#!/usr/bin/env python3
# -*- encoding: utf-8 -*-

# Created by Papillon. Oct 31, 2017.

import datetime
import dbm_field
import dbm_entity
import dbm_config


G_namespace_PREFIX = dbm_config.G_namespace_PREFIX;
G_namespace_prefix = dbm_config.G_namespace_prefix;


def gen_python_class(entity, file_out):
    global G_namespace_PREFIX, G_namespace_prefix;
    entity_name = '{prefix}_{name}'.format(prefix = G_namespace_PREFIX, name = entity.singular_name);
    count = len(entity.fields)
    
    print("class {entity_name}(ctypes.Structure):".format(entity_name = entity_name), file = file_out, end = '\n')
    print("".ljust(4) + "_fields_ = [", file = file_out, end = '\n');
    
    for i in range(0, count):
        field = entity.fields[i];
        separator = ",";
        if (i == count - 1): separator = "";    # the last field has no `,` separator
        field_size = "";
        if (field.length > 0): field_size = " * {length}".format(length = field.length);
        print("".ljust(8) 
              + "(\""
              + "{field_name}\"".format(field_name = field.name).ljust(25)
              + ", {python_type}".format(python_type = field.python_type).ljust(18)
              + "{field_size}".format(field_size = field_size).ljust(8)
              + "){separator}".format(separator = separator).ljust(4)
              + "# [{counter:02}]".format(counter = i),
              file = file_out, end = '\n')
    
    print("".ljust(4) + "]", file = file_out, end = '\n')
    print("", file = file_out, end = '\n' * 2)
    


def gen_entities_for_python(entities, path):
    try:        
        file_out = open(path, mode = "w+", encoding = "utf8")
    except OSError as e:
        print("Failed to open file for writing: " + str(e.errno) + e.strerror) 

    print(r"#!/usr/bin/env python3", file = file_out)
    print(r"# -*- encoding: utf-8 -*-", file = file_out, end = '\n' * 2)    
    print("# Created by Papillon. {now}. ".format(now = datetime.datetime.now().strftime("%c")), file = file_out, end = '\n')
    print("# WARNING: DO NOT EDIT THIS FILE. IT IS GENERATED BY A SCRIPT AUTOMATICALLY. ", file = file_out, end = '\n' * 3)
    print(r"import ctypes", file = file_out)
    print(r"from ctypes import *", file = file_out, end = '\n' * 3)

    for entity in entities:
        gen_python_class(entity, file_out);

    file_out.close()


def main(entities, path):
    gen_entities_for_python(entities, path);
